#!/usr/bin/env python3
"""Merge the Cyrillic glyph atlases into mcufont C sources."""

import re
import sys
from pathlib import Path

from cyrillic_overrides import OVERRIDES


# Two ranges: the main block, plus the pair Ukrainian needs from the extended
# block. mcufont ranges are dense, so a range per contiguous run is cheaper than
# one range spanning the 46 unused slots between them.
RANGES = [(0x0400, 0x045F), (0x0490, 0x0491)]
MARKER = "cyrillic"

# Glyph cells sit at offset_y 0 so accented capitals have a row above the cap
# height for the mark, and descenders still reach below the baseline.
ROLE_CONFIG = {
    "Body": {"height": 10},
    "Subtitle": {"height": 15},
    "Caption": {"height": 6},
}


def covered():
    return {chr(cp) for lo, hi in RANGES for cp in range(lo, hi + 1)}


def encode(role, lo, hi):
    config = ROLE_CONFIG[role]
    glyphs = OVERRIDES[role]

    height = config["height"]
    height_bytes = (height + 7) // 8
    data, offsets, widths = [], [0], []
    for cp in range(lo, hi + 1):
        char = chr(cp)
        advance, rows = glyphs[char]
        width = len(rows[0])
        if len(rows) != height or any(len(row) != width for row in rows):
            raise ValueError(f"invalid {role} override for U+{cp:04X}")

        for x in range(width):
            for byte_index in range(height_bytes):
                value = 0
                for y in range(byte_index * 8, min((byte_index + 1) * 8, height)):
                    if rows[y][x] == "#":
                        value |= 1 << (y - byte_index * 8)
                data.append(value)
        offsets.append(offsets[-1] + width)
        widths.append(advance)

    return data, offsets, widths, height


def format_array(name, values, ctype, columns):
    lines = [f"static const {ctype} {name}[{len(values)}] PROGMEM = {{"]
    for i in range(0, len(values), columns):
        chunk = values[i:i + columns]
        if ctype == "uint8_t":
            rendered = ", ".join(f"0x{value:02x}" for value in chunk)
        else:
            rendered = ", ".join(str(value) for value in chunk)
        lines.append(f"    {rendered},")
    lines.append("};")
    return "\n".join(lines)


def merge(font_path):
    path = Path(font_path)
    source = path.read_text(encoding="ascii")
    role_match = re.search(r"mf_bwfont_(\w+)_glyph_data_0", source)
    if not role_match:
        raise RuntimeError(f"cannot identify font in {path}")
    role = role_match.group(1)
    if role not in ROLE_CONFIG:
        raise RuntimeError(f"unsupported font role {role}")

    glyphs = OVERRIDES[role]
    expected = covered()
    missing = expected.difference(glyphs)
    extra = set(glyphs).difference(expected)
    if missing or extra:
        raise ValueError(
            f"invalid {role} override coverage: "
            f"missing={sorted(missing)!r}, extra={sorted(extra)!r}"
        )

    prefix = f"mf_bwfont_{role}"
    blocks, entries, total = [], [], 0
    for index, (lo, hi) in enumerate(RANGES):
        data, offsets, widths, height = encode(role, lo, hi)
        height_bytes = (height + 7) // 8
        suffix = f"cyr{index}"
        total += len(data)
        blocks.append("\n".join([
            format_array(f"{prefix}_glyph_data_{suffix}", data, "uint8_t", 16),
            format_array(f"{prefix}_glyph_offsets_{suffix}", offsets, "uint16_t", 10),
            format_array(f"{prefix}_glyph_widths_{suffix}", widths, "uint8_t", 16),
        ]))
        entries.append("\n".join([
            "    {",
            f"        {lo}, /* first char */",
            f"        {hi - lo + 1}, /* char count */",
            "        0, /* offset x */",
            "        0, /* offset y */",
            f"        {height_bytes}, /* height in bytes */",
            f"        {height}, /* height in pixels */",
            "        0, /* width */",
            f"        {prefix}_glyph_widths_{suffix}, /* glyph widths */",
            f"        {prefix}_glyph_offsets_{suffix}, /* glyph offsets */",
            f"        {prefix}_glyph_data_{suffix}, /* glyph data */",
            "    },",
        ]))

    arrays = "\n".join(
        [f"/* [{MARKER}] Cyrillic atlas. Generated by build_cyrillic.py. */"]
        + blocks + [f"/* [/{MARKER}] */"]
    )
    entry = "\n".join([f"    /* [{MARKER}] */"] + entries + [f"    /* [/{MARKER}] */"])

    source = re.sub(
        rf"\n?/\* \[{MARKER}\].*?/\* \[/{MARKER}\] \*/\n?",
        "\n",
        source,
        flags=re.S,
    )
    source = re.sub(r"\n{3,}", "\n\n", source)
    table_pattern = rf"({prefix}_char_ranges\[\]\s*=\s*\{{.*?)(\n\}};)"
    table = re.search(table_pattern, source, re.S)
    if not table:
        raise RuntimeError(f"cannot find character range table in {path}")
    range_count = len(re.findall(r"_glyph_widths_", table.group(1))) + len(RANGES)
    count_line = re.search(r"(\d+), /\* char range count \*/", source)
    if not count_line:
        raise RuntimeError(f"cannot find character range count in {path}")
    source = source[:count_line.start()] + f"{range_count}, /* char range count */" + source[count_line.end():]

    anchor = re.search(rf"static (?:const )?struct mf_bwfont_char_range_s {prefix}_char_ranges", source)
    if not anchor:
        raise RuntimeError(f"cannot find character range declaration in {path}")
    source = source[:anchor.start()] + arrays + "\n\n" + source[anchor.start():]
    table = re.search(table_pattern, source, re.S)
    source = source[:table.end(1)] + "\n" + entry + source[table.end(1):]
    source = re.sub(r"[ \t]+$", "", source, flags=re.M)
    source = re.sub(r"\n{3,}", "\n\n", source)
    with path.open("w", encoding="ascii", newline="\n") as output:
        output.write(source)
    spans = ", ".join(f"U+{lo:04X}..U+{hi:04X}" for lo, hi in RANGES)
    print(f"merged {spans} into {path} ({total} bitmap bytes)")


if __name__ == "__main__":
    if len(sys.argv) != 2:
        raise SystemExit("usage: build_cyrillic.py <Body.c|Subtitle.c|Caption.c>")
    merge(sys.argv[1])
