#!/usr/bin/env python3
"""Merge the hand-edited Cyrillic glyph atlases into mcufont C sources."""

import re
import sys
from pathlib import Path

from cyrillic_overrides import OVERRIDES


FIRST = 0x0400
LAST = 0x045F
MARKER = "cyrillic"

ROLE_CONFIG = {
    "Body": {"height": 9, "range_y": 1},
    "Subtitle": {"height": 14, "range_y": 1},
    "Caption": {"height": 6, "range_y": 0},
}


def encode(role):
    config = ROLE_CONFIG[role]
    glyphs = OVERRIDES[role]
    expected = {chr(cp) for cp in range(FIRST, LAST + 1)}
    missing = expected.difference(glyphs)
    extra = set(glyphs).difference(expected)
    if missing or extra:
        raise ValueError(
            f"invalid {role} override coverage: "
            f"missing={sorted(missing)!r}, extra={sorted(extra)!r}"
        )

    height = config["height"]
    height_bytes = (height + 7) // 8
    data, offsets, widths = [], [0], []
    for cp in range(FIRST, LAST + 1):
        char = chr(cp)
        advance, rows = glyphs[char]
        width = len(rows[0])
        if len(rows) != height or any(len(row) != width for row in rows):
            raise ValueError(f"invalid {role} override for U+{cp:04X}")

        for x in range(width):
            for byte_index in range(height_bytes):
                value = 0
                for y in range(byte_index * 8, min((byte_index + 1) * 8, height)):
                    if rows[y][x] == "#":
                        value |= 1 << (y - byte_index * 8)
                data.append(value)
        offsets.append(offsets[-1] + width)
        widths.append(advance)

    return data, offsets, widths, height


def format_array(name, values, ctype, columns):
    lines = [f"static const {ctype} {name}[{len(values)}] PROGMEM = {{"]
    for i in range(0, len(values), columns):
        chunk = values[i:i + columns]
        if ctype == "uint8_t":
            rendered = ", ".join(f"0x{value:02x}" for value in chunk)
        else:
            rendered = ", ".join(str(value) for value in chunk)
        lines.append(f"    {rendered},")
    lines.append("};")
    return "\n".join(lines)


def merge(font_path):
    path = Path(font_path)
    source = path.read_text(encoding="ascii")
    role_match = re.search(r"mf_bwfont_(\w+)_glyph_data_0", source)
    if not role_match:
        raise RuntimeError(f"cannot identify font in {path}")
    role = role_match.group(1)
    if role not in ROLE_CONFIG:
        raise RuntimeError(f"unsupported font role {role}")

    config = ROLE_CONFIG[role]
    prefix = f"mf_bwfont_{role}"
    data, offsets, widths, height = encode(role)
    height_bytes = (height + 7) // 8

    arrays = "\n".join([
        f"/* [{MARKER}] Hand-edited Cyrillic atlas. Generated by build_cyrillic.py. */",
        format_array(f"{prefix}_glyph_data_cyr", data, "uint8_t", 16),
        format_array(f"{prefix}_glyph_offsets_cyr", offsets, "uint16_t", 10),
        format_array(f"{prefix}_glyph_widths_cyr", widths, "uint8_t", 16),
        f"/* [/{MARKER}] */",
    ])
    entry = "\n".join([
        f"    /* [{MARKER}] */",
        "    {",
        f"        {FIRST}, /* first char */",
        f"        {LAST - FIRST + 1}, /* char count */",
        "        0, /* offset x */",
        f"        {config['range_y']}, /* offset y */",
        f"        {height_bytes}, /* height in bytes */",
        f"        {height}, /* height in pixels */",
        "        0, /* width */",
        f"        {prefix}_glyph_widths_cyr, /* glyph widths */",
        f"        {prefix}_glyph_offsets_cyr, /* glyph offsets */",
        f"        {prefix}_glyph_data_cyr, /* glyph data */",
        "    },",
        f"    /* [/{MARKER}] */",
    ])

    source = re.sub(
        rf"\n?/\* \[{MARKER}\].*?/\* \[/{MARKER}\] \*/\n?",
        "\n",
        source,
        flags=re.S,
    )
    source = re.sub(r"\n{3,}", "\n\n", source)
    table_pattern = rf"({prefix}_char_ranges\[\]\s*=\s*\{{.*?)(\n\}};)"
    table = re.search(table_pattern, source, re.S)
    if not table:
        raise RuntimeError(f"cannot find character range table in {path}")
    range_count = len(re.findall(r"_glyph_widths_", table.group(1))) + 1
    count_line = re.search(r"(\d+), /\* char range count \*/", source)
    if not count_line:
        raise RuntimeError(f"cannot find character range count in {path}")
    source = source[:count_line.start()] + f"{range_count}, /* char range count */" + source[count_line.end():]

    anchor = re.search(rf"static (?:const )?struct mf_bwfont_char_range_s {prefix}_char_ranges", source)
    if not anchor:
        raise RuntimeError(f"cannot find character range declaration in {path}")
    source = source[:anchor.start()] + arrays + "\n\n" + source[anchor.start():]
    table = re.search(table_pattern, source, re.S)
    source = source[:table.end(1)] + "\n" + entry + source[table.end(1):]
    source = re.sub(r"[ \t]+$", "", source, flags=re.M)
    source = re.sub(r"\n{3,}", "\n\n", source)
    with path.open("w", encoding="ascii", newline="\n") as output:
        output.write(source)
    print(f"merged U+{FIRST:04X}..U+{LAST:04X} into {path} ({len(data)} bitmap bytes)")


if __name__ == "__main__":
    if len(sys.argv) != 2:
        raise SystemExit("usage: build_cyrillic.py <Body.c|Subtitle.c|Caption.c>")
    merge(sys.argv[1])
